export const TYPES = {
  ResearchDataRepository: Symbol.for('ResearchDataRepository'),
  MarketDataProvider: Symbol.for('MarketDataProvider'),
  CompetitorDataProvider: Symbol.for('CompetitorDataProvider'),
  SearchPhrasesGenerator: Symbol.for('SearchPhrasesGenerator'),
  AutocompleteApi: Symbol.for('AutocompleteApi'),
  AutocompleteDataProvider: Symbol.for('AutocompleteDataProvider'),
  AcademicPapersProvider: Symbol.for('AcademicPapersProvider'),
  ResearchAssistantLlm: Symbol.for('ResearchAssistantLlm'),
  SynthesisLlm: Symbol.for('SynthesisLlm'),
  AssumptionAssessmentLlm: Symbol.for('AssumptionAssessmentLlm'),
  GetResearchCanvasUseCase: Symbol.for('GetResearchCanvasUseCase'),
  GenerateSynthesisUseCase: Symbol.for('GenerateSynthesisUseCase'),
  GenerateAssumptionAssessmentsUseCase: Symbol.for('GenerateAssumptionAssessmentsUseCase'),
  CheckResearchAvailabilityUseCase: Symbol.for('CheckResearchAvailabilityUseCase'),
  CollectResearchDataUseCase: Symbol.for('CollectResearchDataUseCase'),
  HnSearchCommentsCollector: Symbol.for('HnSearchCommentsCollector'),
  RedditSearchCommentsCollector: Symbol.for('RedditSearchCommentsCollector'),
  ResearchAssistantUseCase: Symbol.for('ResearchAssistantUseCase'),
  ResearchController: Symbol.for('ResearchController'),
} as const;
