export const TYPES = {
  ResearchRepository: Symbol('ResearchRepository'),
  ResearchRepositoryPort: Symbol('ResearchRepositoryPort'),
  HttpClientPort: Symbol('HttpClientPort'),
  ResearchPresenter: Symbol('ResearchPresenter'),
  GetResearchCanvasUseCase: Symbol('GetResearchCanvasUseCase'),
  CollectResearchDataUseCase: Symbol('CollectResearchDataUseCase'),
  GenerateSynthesisUseCase: Symbol('GenerateSynthesisUseCase'),
  ResearchAssistantUseCase: Symbol('ResearchAssistantUseCase'),
  CheckResearchAvailabilityUseCase: Symbol('CheckResearchAvailabilityUseCase'),
  GenerateUserStoriesUseCase: Symbol('GenerateUserStoriesUseCase'),
  UserStoriesAiPort: Symbol('UserStoriesAiPort'),
  CommentsFetchStartedEventHandler: Symbol.for('IAsyncEventHandler<CommentsFetchStartedEvent>'),
  CommentsFetchCompletedEventHandler: Symbol.for('IAsyncEventHandler<CommentsFetchCompletedEvent>'),
  ResearchDataCollectionStartedEventHandler: Symbol.for('IAsyncEventHandler<ResearchDataCollectionStartedEvent>'),
} as const;