export const TYPES = {
  ScraperSourceRepository: Symbol.for('ScraperSourceRepository'),
  ScraperRunRepository: Symbol.for('ScraperRunRepository'),
  FetchHtml: Symbol.for('ScraperFetchHtml'),
  FetchHtmlInner: Symbol.for('ScraperFetchHtmlInner'),
  WebScraper: Symbol.for('WebScraper'),
  ScraperSuggestLlm: Symbol.for('ScraperSuggestLlm'),
  ScraperInsightsLlm: Symbol.for('ScraperInsightsLlm'),
  AddScraperSourceUseCase: Symbol.for('AddScraperSourceUseCase'),
  UpdateScraperSourceUseCase: Symbol.for('UpdateScraperSourceUseCase'),
  DeleteScraperSourceUseCase: Symbol.for('DeleteScraperSourceUseCase'),
  ListScraperSourcesUseCase: Symbol.for('ListScraperSourcesUseCase'),
  RunScraperUseCase: Symbol.for('RunScraperUseCase'),
  GetScraperResultsUseCase: Symbol.for('GetScraperResultsUseCase'),
  SuggestScraperUseCase: Symbol.for('SuggestScraperUseCase'),
  GenerateRunInsightsUseCase: Symbol.for('GenerateRunInsightsUseCase'),
  GetScraperStatsUseCase: Symbol.for('GetScraperStatsUseCase'),
  GetScraperDashboardMetricsUseCase: Symbol.for('GetScraperDashboardMetricsUseCase'),
  ScraperController: Symbol.for('ScraperController'),
} as const;
